# Generated by Django 4.0.6 on 2022-07-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='DT',
            field=models.DateTimeField(null=True),
        ),
    ]
