# Generated by Django 4.0.6 on 2022-07-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpart', '0002_alter_post_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='IMG',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
