# Generated by Django 4.0.6 on 2022-07-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpart', '0003_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='IMG',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
